# Generated by Django 4.1.3 on 2022-11-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна происхождения'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kitchen', verbose_name='Кухня мира')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
    ]
